sudo: required
dist: trusty

language: cpp

git:
    depth: 1

env:
  global:
    - secure: "dkQzxuKiFCzMS0BCwJujjsA2ztk4ppnfpyIX0cGqnVm3H+aTgTo210dLKxUdkG7bt/Gp6iYl9g+1DxT12+XiSohswSMvpl91RDqG3Sirlukf2+tmjmY1i4jNrX9vbCszUFNHTmCsG/6x+JJhcQuJmJrNAc6Nqgo/309k8sqyVxRZj90IBdUrfZbifawn96VwkD1y1SNqzEk61HgVPVBMyx/bK3yv6rBgHOHeoYjDw9Eg4D/9GjkgkRVYqYzKRRiTSDLXJ3xN3E6ouWVME1iglKhrur6d31z30Dmro8LYcmP0bqBN9A/h2Axk5Ga+7W+E60w5LrPmYDQ91N9IEi+nSWXooMDNfUOSRJ5dYQGgd2vj208u/WirLnzUNax9LocecTm65Kj7lLrPyUrArLBf6kN8hODSNdxK8Ci4mcGC6Fa+mwMaDTVkPv85sueGquTMbYwtJkhY/ylYXNdzcjCvCUbrZVyPcUNcDIlZf504cBPMsUCarngWsFm8zp+lK3YQs2KA4Dn7IZgCgOJ+Kyk8pT3vgAPUy8Fs0GNM7LZMUNzD/oDo+rQt91HMI1/OX0L6GY53xeClA8oHPQteGcqd7ADC1GQ/hg4EYzg30vlwEy71TpNBhmgbjwgSm2luyfO0qdI6Y7wVPlzhKLl48AL0JmR5ydnWxK0WaCyW21rwlNw="
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: linux
      compiler: gcc
      env: CMAKE_ARGS="-DAndroid=1 -DCMAKE_TOOLCHAIN_FILE=../Android.cmake -Dtools=$HOME/android-toolchain/"

addons:
  coverity_scan:
    project:
      name: "pjasicek/CaptainClaw"
      description: "Build submitted via Travis CI"
    notification_email: pjasicek@gmail.com
    build_command_prepend: "mkdir build; cd build; cmake .."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    - sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-gfx-dev
    - sudo apt-get install libtinyxml-dev
    - sudo apt-get install cmake
    - git clone 'https://github.com/loblik/captainclaw-arm-linux-androideabi-4.9.git' ~/android-toolchain
    - git config user.email "travis@build.bot" && git config user.name "Travis CI"
    - git tag -a -m "Travis build" init

#install:

script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mkdir build; cd build; cmake $CMAKE_ARGS .. ; fi
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make -j8 ; fi

